<?php

/**
 * @file
 * Agreement module code - agreement.module.
 *
 * Module allows the administrator to force a user role to accept an agreement
 * before accessing any site content.
 */


use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_user_update().
 */
function agreement_user_update(EntityInterface $account) {
  /** @var \Drupal\user\Entity\User $account */
  if ($account->getEntityTypeId() === 'user') {
    $current_user = \Drupal::currentUser();
    $agreements = \Drupal::entityTypeManager()->getStorage('agreement')->loadMultiple();
    /** @var \Drupal\agreement\Entity\Agreement $agreement */
    foreach ($agreements as $agreement) {
      if (!$agreement->agreeOnce() &&
          $account->original->get('pass') === $account->get('pass') &&
          $current_user->id() === $account->id()) {
        \Drupal::service('agreement.handler')->agree($account, $agreement, 2);
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function agreement_theme($existing, $type, $theme, $path) {
  return array(
    'agreement_page' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Implements hook_mail().
 */
/**
function agreement_mail($key, &$message, $params) {
  switch ($key) {
    case 'notice':
      $variables = array(
        '!site-name' => variable_get('site_name', 'Drupal'),
        '!username' => format_username($params['account']),
      );
      $message['subject'] = t('!site-name: !username accepted agreement', $variables, array('langcode' => $message['language']->language));
      $message['body'][] = t('The user has accepted the agreement.');
      break;
  }
}
 */

/**
 * Format the agreement page.
 *
 * @ingroup themeable
 */
function theme_agreement_page(&$variables) {
  return $variables['form'];
}
